### ISSUE TITLE
ADC internal reference reading stops working after reading ADC channel 18 or read_core_vbat()

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Firmware#1]
a = pyb.ADCAll(12)
a.read_channel(0)  #USB voltage
a.read_channel(17) #internal reference - will read ~1600
a.read_channel(18) # or a.read_core_vbat()
a.read_channel(17) #this will now always be junk
a.read_channel(0) #will still read OK

**Comment by thinkl33t** [comment]
This was a bug on the F4 - no longer valid
