### ISSUE TITLE
Test increasing CC3100 SPI Speed

### ISSUE THREAD

**Issue by drrk** [emfcamp/Mk3-Firmware#5]
It's quite low atm, from my testing with 10cm cables.  Now it is correctly working on board, we should increase the transfer speed

**Comment by drrk** [comment]
Done, it's running at full speed on mine.

**Comment by dpslwk** [comment]
What's full speed?

'RepRap' Matt

**Comment by drrk** [comment]
HAL_RCC_GetPCLK1Freq() /2

Which is 80000000/2 or 40MHz
