### ISSUE TITLE
IOError in lib/imu.py is not defined

### ISSUE THREAD

**Issue by philcrump** [emfcamp/Mk3-Firmware#66]
Error triggered by running latest master on a yellow prototype board without an IMU fitted.

> Traceback (most recent call last): File "main.py", line 4, 
>                     in <module> File "apps/home/main.py", line 95, in <module> 
>                     File "/flash/lib/imu.py", line 32, in __init__
> NameError: name 'IOError' is not defined

**Comment by thinkl33t** [comment]
Looks like IOError isn't raisable from python - Fixed in cd3a23b82573e2b14b505f52f647e604cda8d050
